"use client";

import { useState } from "react";
import { UploadCloud, FileText, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { uploadDocumentAction } from "@/app/(dashboard)/actions";
import { useI18n } from "@/lib/i18n/provider";

export default function FilesPage() {
  const { t } = useI18n(); const [ok, setOk] = useState(false); const [file, setFile] = useState<File | null>(null); const [type, setType] = useState("company"); const [relatedId, setRelatedId] = useState(""); const [status, setStatus] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  async function upload() { if (!file) return; setBusy(true); setStatus(null); const form = new FormData(); form.set("file", file); form.set("relatedType", type); form.set("relatedId", relatedId); const result = await uploadDocumentAction(form).catch(() => ({ errorCode: "errGeneric" } as { errorCode: string; name?: string })); const failed = "errorCode" in result && !!result.errorCode; setOk(!failed); setStatus(failed ? t((result as { errorCode: string }).errorCode as never) : `${t("uploadedOk")} ${(result as { name?: string }).name ?? ""}`); setBusy(false); }
  return <div className="p-4 md:p-8 max-w-2xl mx-auto"><div className="mb-6"><h1 className="text-xl font-bold">{t("navFiles")}</h1><p className="text-sm text-slate-500">{t("filesSubtitle")}</p></div><div className="rounded-xl border border-slate-200 bg-white p-5 space-y-4"><label className="block cursor-pointer rounded-xl border-2 border-dashed border-slate-300 p-8 text-center hover:border-brand-400"><UploadCloud className="mx-auto mb-2 h-9 w-9 text-brand-600" /><p className="text-sm font-medium">{t("chooseFile")}</p><p className="mt-1 text-xs text-slate-400">{t("fileTypesHint")}</p><input type="file" accept="application/pdf,image/jpeg,image/png,image/webp" className="hidden" onChange={(e) => setFile(e.target.files?.[0] || null)} /></label>{file && <p className="text-sm text-slate-600">{t("fileSelected")} <strong>{file.name}</strong></p>}<select aria-label={t("relatedType")} value={type} onChange={(e) => setType(e.target.value)} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value="company">{t("relCompany")}</option><option value="client">{t("relClient")}</option><option value="project">{t("relProject")}</option><option value="quote">{t("relQuote")}</option><option value="purchase_order">{t("relPO")}</option><option value="expense">{t("relExpense")}</option></select><input value={relatedId} onChange={(e) => setRelatedId(e.target.value)} aria-label={t("relatedIdPh")} placeholder={t("relatedIdPh")} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm" /><Button type="button" disabled={!file || busy} loading={busy} onClick={upload} className="w-full">{t("uploadSecurely")}</Button>{status && <p role="status" className={`text-sm ${ok ? "text-green-600" : "text-red-600"}`}>{status}</p>}</div><div className="mt-4 flex gap-2 rounded-xl border border-green-100 bg-green-50 p-4 text-sm text-green-800"><ShieldCheck className="h-5 w-5 shrink-0" /><span>{t("filesSecurityNote")}</span></div></div>;
}
