"use client";

import { useMemo } from "react";
import { BarChart3, Download, FileText, Receipt, TrendingUp, Briefcase } from "lucide-react";
import { PageHeader } from "@/components/shared/PageHeader";
import { Button } from "@/components/ui/Button";
import { formatCurrency } from "@/lib/utils";
import { useI18n } from "@/lib/i18n/provider";
import type { Dictionary } from "@/lib/i18n/dictionaries/es";

const STATUS_KEYS: Record<string, keyof Dictionary> = { lead: "statusLead", quoted: "statusQuoted", approved: "statusApproved", active: "statusActive", on_hold: "statusOnHold", completed: "statusCompleted", cancelled: "statusCancelled" };
type Data = { metrics?: { totalContractValue: number; totalProfit: number; pendingQuotes: number; pendingInvoices: number; expensesThisMonth: number }; projects?: { status: string; name: string; contract_value: number; spentTotal: number }[]; quotes?: { status: string; total: number }[]; invoices?: { status: string; total: number; amount_paid: number }[]; expenses?: { amount: number; vendor_name?: string | null; category?: { name?: string } | null }[] };
export default function ReportsClient({ metrics, projects = [], quotes = [], invoices = [], expenses = [], demo = false }: Data & { demo?: boolean }) { const { t } = useI18n(); const statusLabel = (s: string) => { const k = STATUS_KEYS[s]; return k ? t(k) : s; }; const m = metrics || { totalContractValue: 0, totalProfit: 0, pendingQuotes: 0, pendingInvoices: 0, expensesThisMonth: 0 }; const totalExpenses = expenses.reduce((sum, e) => sum + Number(e.amount), 0); const totalSales = quotes.filter((q) => q.status === "approved").reduce((sum, q) => sum + Number(q.total), 0); const overdue = invoices.filter((i) => i.status === "overdue").reduce((sum, i) => sum + Math.max(0, Number(i.total) - Number(i.amount_paid)), 0); const jobs = useMemo(() => projects.reduce<Record<string, number>>((acc, p) => { acc[p.status] = (acc[p.status] || 0) + 1; return acc; }, {}), [projects]); function exportCsv() { const rows = [[t("repMetric"), t("repValue")], [t("repContractedSales"), m.totalContractValue], [t("repApprovedQuotes"), totalSales], [t("repExpenses"), totalExpenses], [t("repEstProfit"), m.totalProfit], [t("repPendingInvoices"), m.pendingInvoices], [t("repOverdueInvoices"), overdue], ...Object.entries(jobs).map(([status, count]) => [`${t("repJobsPrefix")} ${statusLabel(status)}`, count])]; const blob = new Blob(["\uFEFF" + rows.map((row) => row.join(",")).join("\r\n")], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = "bidpower-report.csv"; a.click(); URL.revokeObjectURL(url); }
  const cards = [{ label: t("repContractedSales"), value: formatCurrency(m.totalContractValue), icon: TrendingUp }, { label: t("repApprovedQuotes"), value: formatCurrency(totalSales), icon: FileText }, { label: t("repExpenses"), value: formatCurrency(totalExpenses), icon: Receipt }, { label: t("repEstProfit"), value: formatCurrency(m.totalProfit), icon: BarChart3 }, { label: t("repPendingInvoices"), value: String(m.pendingInvoices), icon: FileText }, { label: t("repOverdueInvoices"), value: formatCurrency(overdue), icon: Receipt }]; return <div className="p-4 md:p-8"><PageHeader title={t("reports")} action={<Button variant="outline" size="sm" onClick={exportCsv}><Download className="w-4 h-4" />{t("exportReports")}</Button>} />{demo && <div role="alert" className="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{t("errLoadData")}</div>}<div className="grid grid-cols-2 md:grid-cols-3 gap-3 mb-6">{cards.map((card) => <div key={card.label} className="rounded-xl border border-slate-200 bg-white p-4"><card.icon className="mb-2 h-4 w-4 text-brand-600" /><p className="text-xs text-slate-500">{card.label}</p><p className="mt-1 text-xl font-bold">{card.value}</p></div>)}</div><div className="grid md:grid-cols-2 gap-4"><div className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="mb-4 flex items-center gap-2 font-semibold"><Briefcase className="h-4 w-4" />{t("repJobsByStatus")}</h2>{Object.keys(jobs).length === 0 ? <p className="text-sm text-slate-400">{t("repNoJobs")}</p> : Object.entries(jobs).map(([status, count]) => <div key={status} className="flex justify-between border-b border-slate-50 py-2 text-sm"><span>{statusLabel(status)}</span><strong>{count}</strong></div>)}</div><div className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="mb-4 font-semibold">{t("repQuoteConversion")}</h2><div className="space-y-2 text-sm"><div className="flex justify-between"><span>{t("repTotalQuotes")}</span><strong>{quotes.length}</strong></div><div className="flex justify-between"><span>{t("repApproved")}</span><strong>{quotes.filter((q) => q.status === "approved").length}</strong></div><div className="flex justify-between"><span>{t("repPending")}</span><strong>{m.pendingQuotes}</strong></div></div></div></div></div>; }
