"use client";

import Link from "next/link";
import { ArrowLeft, CheckCircle, DollarSign } from "lucide-react";
import { useState } from "react";
import { formatCurrency } from "@/lib/utils";
import { Button } from "@/components/ui/Button";
import { recordInvoicePaymentAction } from "@/app/(dashboard)/actions";
import { useI18n } from "@/lib/i18n/provider";
import { invoiceStatusKey } from "@/lib/invoice-status";

type Invoice = { id: string; number: string; status: string; total: number; amount_paid: number; issue_date?: string; due_date?: string | null; notes?: string | null; client?: { name?: string } | null; project?: { name?: string } | null; items?: { id: string; description: string; quantity: number; unit_price: number; amount: number }[] };
export default function InvoiceDetailClient({ invoice }: { invoice: Invoice }) {
  const { t } = useI18n(); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [payment, setPayment] = useState(""); const i = invoice; const balance = Math.max(0, Number(i.total) - Number(i.amount_paid));
  async function pay(amount: number) { if (amount <= 0) return; setBusy(true); const form = new FormData(); form.set("invoiceId", i.id); form.set("amount", String(amount)); const r = await recordInvoicePaymentAction(form).catch(() => ({ errorCode: "errGeneric" })); setBusy(false); if (r && "errorCode" in r && r.errorCode) { setError(t(r.errorCode as never)); return; } window.location.reload(); }
  return <div className="p-4 md:p-8 max-w-2xl mx-auto"><div className="flex items-center gap-3 mb-6"><Link href="/invoices" className="w-9 h-9 rounded-full bg-slate-100 flex items-center justify-center"><ArrowLeft className="w-4 h-4" /></Link><div className="flex-1"><p className="text-xs text-slate-400">{i.number}</p><h1 className="text-lg font-bold">{i.client?.name || t("noClient")}</h1></div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-medium">{t(invoiceStatusKey(i.status))}</span></div><div className="grid grid-cols-3 gap-2 mb-4"><div className="rounded-xl border border-slate-200 bg-white p-3"><p className="text-xs text-slate-500">{t("total")}</p><p className="font-bold">{formatCurrency(Number(i.total))}</p></div><div className="rounded-xl border border-slate-200 bg-white p-3"><p className="text-xs text-slate-500">{t("paid")}</p><p className="font-bold text-green-600">{formatCurrency(Number(i.amount_paid))}</p></div><div className="rounded-xl border border-slate-200 bg-white p-3"><p className="text-xs text-slate-500">{t("balance")}</p><p className="font-bold text-amber-600">{formatCurrency(balance)}</p></div></div><div className="mb-4 rounded-xl border border-slate-200 bg-white p-5"><h2 className="mb-3 font-semibold">{t("invoiceItems")}</h2>{(i.items || []).map((item) => <div key={item.id} className="flex justify-between border-b border-slate-50 py-3 text-sm"><span>{item.description} · {item.quantity} × {formatCurrency(Number(item.unit_price))}</span><strong>{formatCurrency(Number(item.amount))}</strong></div>)}{i.notes && <p className="mt-4 text-sm text-slate-500">{i.notes}</p>}</div>{balance > 0 && <div className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="mb-3 flex items-center gap-2 font-semibold"><DollarSign className="w-4 h-4" />{t("recordPayment")}</h2><div className="flex gap-2"><input type="number" min="0.01" max={balance} step="0.01" value={payment} onChange={(e) => setPayment(e.target.value)} aria-label={t("amount")} placeholder={t("amount")} className="flex-1 rounded-lg border border-slate-200 px-3 py-2 text-sm" /><Button disabled={busy} onClick={() => pay(Number(payment))}>{t("recordPaymentBtn")}</Button></div><Button disabled={busy} variant="outline" className="mt-3 w-full" onClick={() => pay(balance)}>{t("markPaidFull")}</Button>{error && <p role="alert" className="mt-3 text-sm text-red-600">{error}</p>}</div>}{balance === 0 && <div className="flex items-center gap-2 rounded-xl bg-green-50 p-4 text-sm text-green-700"><CheckCircle className="w-4 h-4" />{t("paidInFull")}</div>}</div>;
}
